// Copyright Epic Games, Inc. All Rights Reserved.

#pragma once

#include "CoreMinimal.h"
#include "RhubarbFaceActorBase.h"
#include "DynamicSpeechTestActor.generated.h"

// Phase 2a test actor: simulates receiving an audio chunk from the backend (editor button
// loading a local .wav into memory) to validate the client pipeline independently of HTTP.
// ProcessIncomingAudioChunk is the same entry point the real HTTP callback will use later, 
// only the byte source changes. LiveLink driving (mouth curves + idle animation,
// BeginPlay/EndPlay/Tick) comes entirely from ARhubarbFaceActorBase, no need to override it here.
UCLASS()
class REALTIMELIPSYNC_API ADynamicSpeechTestActor : public ARhubarbFaceActorBase
{
	GENERATED_BODY()

public:
	// Overrides only LipSyncDelaySeconds (calibrated to 0.2s here, see ARhubarbFaceActorBase for
	// the 0.f default). Everything else in construction comes from the base class.
	ADynamicSpeechTestActor();

	// Local .wav file used to simulate a chunk received from the backend (e.g. a phrase
	// already generated by ElevenLabs in Phase 1, reused as-is for this test).
	UPROPERTY(EditAnywhere, Category = "RhubarbLipSync|Test")
	FFilePath TestWavPath;

	// Loads TestWavPath into memory and calls ProcessIncomingAudioChunk with its bytes,
	// exactly like the real HTTP callback will do later with the response body.
	UFUNCTION(CallInEditor, Category = "RhubarbLipSync|Test")
	void SimulateIncomingChunk();

	// PHP middleware root (scheme+host, no /api/v1), adjust to wherever the test backend
	// runs (e.g. "http://localhost:8080" for `php -S`, or the real host).
	UPROPERTY(EditAnywhere, Category = "RhubarbLipSync|Backend")
	FString BackendBaseUrl = TEXT("http://localhost:8080");

	// Text sent to /api/v1/ai/tts for this test.
	UPROPERTY(EditAnywhere, Category = "RhubarbLipSync|Backend")
	FString TextToSpeak = TEXT("The mysterious professor whispered quietly at first, then suddenly shouted with joy, waving his umbrella boldly above his head. He had wandered through the foggy old library for hours, mumbling strange words under his breath, before finally discovering a dusty book that promised to reveal the secret that had baffled the entire village for almost thirty years. Overwhelmed with excitement, he rushed outside, laughing and shouting, determined to tell the whole world before another rival scholar could steal the glory.");

	// Gets a session (sid+secret, cached for later calls), signs and sends
	// GET /api/v1/ai/tts?q=...&fmt=wav, then feeds ProcessIncomingAudioChunk with the response
	// body. Same entry point as SimulateIncomingChunk, only the byte source changes (network
	// instead of a local file).
	UFUNCTION(CallInEditor, Category = "RhubarbLipSync|Backend")
	void RequestSpeechFromBackend();

private:
	// Signs and sends the GET /api/v1/ai/tts request once sid+secret are available (CachedSid/
	// CachedSecretHex already filled by RequestSpeechFromBackend), then passes the response to
	// ProcessIncomingAudioChunk (inherited from ARhubarbFaceActorBase, see RhubarbFaceActorBase.h).
	void SendSignedTtsRequest();

	// HMAC session cached after the first successful RequestSession call, to avoid redoing
	// /session/id + /session/secret on every click of the test button.
	FString CachedSid;
	FString CachedSecretHex;
	bool bHasSession = false;
};
